
openapi: 3.0.0
info:
  title: Azure Summarizer API
  version: 1.0.0
paths:
  /api/summarize:
    post:
      summary: Summarize text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        '200':
          description: Summary returned
        '400':
          description: Bad Request
        '500':
          description: Server Error
